language: node_js
node_js:
  - '4'
sudo: required
cache:
  directories:
    - node_modules
env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
    - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta
    - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower
  - npm install -g codeclimate-test-reporter
install:
  - npm install
  - bower install
script:
  - 'ember try:one $EMBER_TRY_SCENARIO --- ember test'
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  code_climate:
    repo_token: <CODE_CLIMATE_TOKEN_GOES_HERE>
after_script:
  - codeclimate-test-reporter < lcov.dat
